"""Repository protocols for workspace and artifact data access."""

from __future__ import annotations

from typing import Protocol

from workspace_service.models.domain import ArtifactDomain, WorkspaceDomain


class WorkspaceRepository(Protocol):
    """Interface for workspace metadata persistence."""

    async def create(self, workspace: WorkspaceDomain) -> None: ...

    async def get(self, workspace_id: str) -> WorkspaceDomain | None: ...

    async def get_by_local_path_key(self, local_path_key: str) -> WorkspaceDomain | None: ...

    async def list_by_tenant_user(self, tenant_id: str, user_id: str) -> list[WorkspaceDomain]: ...

    async def update_last_active(self, workspace_id: str) -> None: ...

    async def delete(self, workspace_id: str) -> None: ...


class ArtifactRepository(Protocol):
    """Interface for artifact metadata persistence."""

    async def create(self, artifact: ArtifactDomain) -> None: ...

    async def get(self, workspace_id: str, artifact_id: str) -> ArtifactDomain | None: ...

    async def list_by_workspace(self, workspace_id: str) -> list[ArtifactDomain]: ...

    async def list_by_session(self, workspace_id: str, session_id: str) -> list[ArtifactDomain]: ...

    async def delete(self, workspace_id: str, artifact_id: str) -> None: ...

    async def delete_by_workspace(self, workspace_id: str) -> None: ...


class ArtifactStore(Protocol):
    """Interface for artifact content storage (S3)."""

    async def upload(self, s3_key: str, content: bytes, content_type: str) -> None: ...

    async def download(self, s3_key: str) -> bytes: ...

    async def delete(self, s3_key: str) -> None: ...

    async def delete_prefix(self, prefix: str) -> None: ...
